image:
  file: assets/gitpod/Dockerfile
tasks:
  - name: Install project
    init: |
      composer install --prefer-install=auto
ports:
  - port: 80
    onOpen: open-preview

vscode:
  extensions:
    - felixfbecker.php-debug
    - wongjn.php-sniffer
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    - mblode.twig-language-2
    - timonwong.shellcheck
    - rogalmic.bash-debug
