image:
  file: assets/gitpod/Dockerfile
tasks:
  - name: Install project
    env:
      GITPOD_REPO_ROOT: /workspace/verbruggenalex/web
    init: |
      composer install --prefer-install=auto
      composer drupal-install
    command: |
      sudo service apache2 start
ports:
  - port: 80
    onOpen: open-preview

vscode:
  extensions:
    - felixfbecker.php-debug
    - wongjn.php-sniffer
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    - mblode.twig-language-2
    - timonwong.shellcheck
    - rogalmic.bash-debug
