image:
  file: assets/gitpod/Dockerfile
tasks:
  - name: Install project
    env:
      APACHE_DOCROOT_IN_REPO: web
    init: |
      composer install --prefer-install=auto
      composer drupal-install
    command: |
      sudo service apache2 start
ports:
  - port: 80
    onOpen: open-preview

vscode:
  extensions:
    - felixfbecker.php-debug
    - wongjn.php-sniffer
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    - mblode.twig-language-2
    - timonwong.shellcheck
    - rogalmic.bash-debug

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true